language: node_js
sudo: false
dist: trusty

node_js:
  - "10"

cache:
  directories:
    - node_modules

git:
  depth: 10

jobs:
  include:
    - stage: Static Test
      env:
        - test: Editor Config check
      install:
      - npm i -g eclint
      script:
      - eclint check
    - stage: Static Test
      env:
        - test: Dockerfile_lint
      install:
      - npm i -g dockerfile_lint
      script:
      - dockerfile_lint
